### ISSUE TITLE
fatal: empty string is not a valid pathspec

### ISSUE THREAD

**Issue by davewongillies** [puppetlabs/r10k#801]
When using git 2.16 or greater, [having an empty string for a pathspec is no longer valid](https://github.com/git/git/commit/d426430e6ec2a05bf0a4ee88c319dd6072908504). This shows up in r10k with an error like so:

```
ERROR	 -> Command exited with non-zero exit code:
Command: git --git-dir /Source/puppet/modules/gnupg/.git --work-tree /Source/puppet/modules/gnupg checkout 913d8235063bd4f785578887b8791096d9f8149f 
Stderr:
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
Exit code: 128
```

**Comment by ecirtap** [comment]
Same for me, it may be more and more problematic for R10K as git versions are evolving naturally in different OS (still fine on MacOS native where git version is 2.7.4 on High-Sierra but not OK if using the brew version, no more OK on Ubuntu 18.04 where it is 2.17.1 etc ...).

**Comment by rbywater** [comment]
It seems that with Git 2.18.0 and r10k 2.6.2 this is not happening anymore for me. Not sure which of the two has fixed the issue.

**Comment by Magisus** [comment]
I think this was fixed upstream with Git. We hadn't done anything to address it, because we were still using an older version of Git internally.

**Comment by natesilverman** [comment]
still happens for me on Ubuntu 18.04 w/git 2.21.0 and r10k 2.6.2

**Comment by mwaggett** [comment]
Closing this issue since it appears to have been fixed upstream.

**Comment by DendyGG** [comment]
> Closing this issue since it appears to have been fixed upstream.

OPEN THIS
